# Generated by Django 5.0.6 on 2024-07-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='student_name',
        ),
    ]
